### ISSUE TITLE
Sync is so slow.

### ISSUE THREAD

**Issue by lambda2003** [etclabscore/core-geth#70] opened 2020-03-16 01:17 UTC
Geth version: v1.11.1
OS & Version: Ubuntu

I tried to download all blocks as full sync. It was fast but sync speed was so slow in some point at 9670000. Am I doing wrong?? Any help/comment will help me a lot. Thank you for your support as always. :)

======================
current block
======================
currentBlock: 9679390,
highestBlock: 9679544,
knownStates: 489292493,
pulledStates: 489292493,
startingBlock: 9679469

======================
Below is my log file.
======================
   76: cumulative: 4977974 gas: 21000 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0x9e800c550ee5dbdaa2d10277e41e8a1e1eca8fce78ffe49                                                       3ba1d7162ab79b4bc logs: [] bloom: 0000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       000000000000000000000000000000000000000000000000000000000000000000 state:
         77: cumulative: 5014563 gas: 36589 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0xfdcd94cc07c31277ab928b274a1e9fc5f06b3aa906fc112                                                       873f6c3f16687315c logs: [0xc028254e70] bloom: 0000000000000010000000000000100000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000040000008000000000000000000000010000000000000000000                                                       00000000000000000000020000000000000000000000000080001000000000000000000000000000                                                       00000000000000000000000000000000000000000000008000000000000000000200000000000000                                                       00000000000000000000000000000000000002000000000000000000000004000000000000000000                                                       000000000000000000000000000000000000000000000000000000000000000000000000000000 s                                                       tate:
         78: cumulative: 5055772 gas: 41209 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0xec0e835ec6ce56cbb98ae42c6fe7dca81ea422b4da4be0d                                                       e6b6c4944e2cb3411 logs: [0xc028254f20] bloom: 0100000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000100000000000000000000                                                       00000000000000000000000008000000000008000010000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000001000000000000000000000000000                                                       00000000000000000000000000000000000000001000000000000000000001000000800000000000                                                       00000000000000000000000000000000000002000000000000000000000000000000000000000000                                                       000000000000000000000000000000000000000000000000000000000008000000000000020000 s                                                       tate:
         79: cumulative: 5095064 gas: 39292 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0x62782156aab13733cea691568d38407935a2973da6cb5e8                                                       5d28927562adb25e4 logs: [0xc028254fd0] bloom: 0000000000000000000000000000000000                                                       00000000000008000000000000000004000000000000000000000000000000000000000000000000                                                       00000000001000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000100                                                       00000000000000000000000000000004000008000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000004000000000000000000000000000000000000001                                                       000000000000000000000000000000000000000000000000000000000000000000000000000000 s                                                       tate:
         80: cumulative: 5146248 gas: 51184 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0x8e835a4e242dca38928088b7be1767e1b67e583e6568c39                                                       0d600c13f5b72a069 logs: [0xc028255080] bloom: 0000000000000000000000000000000000                                                       00000000000000000000000000800000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000080000008000000000000000000000000000000000000000000                                                       00000000000000000000400000000020000000000000000000001000000000000080000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000802000020000000000000000000000000000000000000                                                       000000000000000000000000000000000800000000000000000000000000000000000040000000 s                                                       tate:
         81: cumulative: 5182972 gas: 36724 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0x94a95cae19d3201e1785befae22922111239a8f7f7f6ca6                                                       758ef4af09b042128 logs: [0xc028255130] bloom: 0000000000000000000000000000000000                                                       00000000000000000000000000000000000000000020000000000000000000000000000000000000                                                       40000000000000000000000000000000000008000000020000080000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000001000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000800000000                                                       00000000000000000000000000000100000002000000000000000000000000000000000000000001                                                       000000000000000000004000000000000000000000000000000000000000000008000000000000 s                                                       tate:
         82: cumulative: 5203972 gas: 21000 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0x6d85da52259712109f1c9c7d63b335f7a713d858ef911f8                                                       5519b5b8a9fb2bb9f logs: [] bloom: 0000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       000000000000000000000000000000000000000000000000000000000000000000 state:
         83: cumulative: 5224972 gas: 21000 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0xa4a958965f7d5fdc5b07a0e8b9b925775a14457111ffd47                                                       5af8812e643573f60 logs: [] bloom: 0000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       000000000000000000000000000000000000000000000000000000000000000000 state:
         84: cumulative: 5505330 gas: 280358 contract: 0x00000000000000000000000                                                       00000000000000000 status: 1 tx: 0x05cf5ec99628ed509e2f1bd38055eaec8c1e3c84d125fb                                                       154b2d502d0552c657 logs: [0xc0282551e0] bloom: 000000000000000000000000000000000                                                       00000000000020000000000000000000000000000000000000000000000000000000000000000200                                                       00000000020000000000000010000000000000000000000400000000000800000000000010000000                                                       00000400000000400000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000001000000000220000000000000000000800000000000000000000000000000                                                       00000000000000000000000000001000000000000000000000000000000000000000000000000000                                                       0000000000000000000000000000000000000000000000000000000000000000000000000800000                                                        state:
         85: cumulative: 5526330 gas: 21000 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0x97ea613d80a11d900b059324815d75c218ae4a150b3cd44                                                       afba3c7f4d96d4491 logs: [] bloom: 0000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       000000000000000000000000000000000000000000000000000000000000000000 state:
         86: cumulative: 9872024 gas: 4345694 contract: 0x0000000000000000000000                                                       000000000000000000 status: 1 tx: 0x7a7fcd659845ed53f7b48085e1c2dfe118f9e2ff1be98                                                       4415ec978cd9c46e77d logs: [] bloom: 00000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000 state:
         87: cumulative: 9918447 gas: 46423 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0xd45c0654365aa32d7bc03f53574aafe427db8d7547c1aa8                                                       619e1061dfdad08d7 logs: [0xc028255290] bloom: 0000000000000000000000000000000000                                                       00000000000008100000000000000000000000000000000000000000000000000000000000000000                                                       00000000001000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000180000000000000000000002000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000100000000000004000008000000000000000000000000000000000                                                       000000000000000000000000000000000000000000000000000000000000000000000000000000 s                                                       tate:
         88: cumulative: 9943010 gas: 24563 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0x95281c89c3329bf9b23abfa575f71bb97e962e9de147889                                                       cc92b455a4746339d logs: [0xc028255340] bloom: 0000000000000000000000000000000000                                                       00000000000000000000000000000000000000080000000000000000000000000000000000800000                                                       00000000000000000000000000000000000008000000000000000000000000000000000000000000                                                       00000040000000000000000000000000000000000000000000001000000000000000000000000000                                                       00000000000000800000000000000000800000000000000000000008000000000000000000008000                                                       00000000000000000000000000000000000002000000000000000000000000000000000000000000                                                       000000001000000000000000000000000000000000000000000000000000000000000000020000 s                                                       tate:
         89: cumulative: 9965351 gas: 22341 contract: 0x000000000000000000000000                                                       0000000000000000 status: 1 tx: 0xbddf164efd0591a89e939caea97f8974db4ec1afe18c8bc                                                       54e06ce034df209de logs: [0xc0282553f0] bloom: 0000000000000000000000000000000000                                                       00008000000000000000000000000000000000000000000000080000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000400000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00000000000000000000000000000000000000000000000000000000000000000000000000000000                                                       00002000000000000000000000000000000000000000000000000000000040000000000000010000                                                       000000000000000000000000000000000000000000000000000000000000000000000000000000 s                                                       tate:

Error: invalid merkle root (remote: eb16844aad70eaa03cd24e0c3a06447baa72fd6858dd                                                       0f41fe462a7d8b62a1ef local: 63cd7f2d28b429de5ac471570d1ed5c2cc768ac94262537eb203                                                       9678d79f4193)
##############################

WARN [03-16|01:10:08.737] Synchronisation failed, dropping peer    peer=8165f2a6                                                       2cebd2f4 err="retrieved hash chain is invalid"

**Comment by meowsbits** [comment] 2020-03-16 14:05
Can you please show
- output of `geth version`
- what command you're using to run `geth`
- more logs (maybe as a [gist](https://gist.github.com/)

This will help us help you ;)

**Comment by lambda2003** [comment] 2020-03-20 01:30
version: 1.11.1-stable-159fbaa2

command: geth --verbosity 3 --rpc --rpcaddr 0.0.0.0 --rpccorsdomain * --allow-insecure-unlock --rpcvhosts xxxxx.com --rpcapi db,eth,net,web3,personal --ws --wsorigins *


> eth.blockNumber;
9679390
> eth.syncing;
{
  currentBlock: 9679390,
  highestBlock: 9705634,
  knownStates: 489292493,
  pulledStates: 489292493,
  startingBlock: 9705612
}



LOG:
https://gist.github.com/lambda2003/651f0234602cdc33f3a4ba9d9cfb416c

**Comment by lambda2003** [comment] 2020-03-23 02:48
@meowsbits Thank you for your help. Mine is stuck in 9679390 block. Any suggestion or advice??

I just updated 1.11.1 version to 1.11.2. But I still have the same issue. Here is my recent log file. 

Version:  1.11.2-stable-cbe4a649
https://gist.github.com/lambda2003/44a3c69b0154141640036d4fb31823bd

I can see below in my log file. Is it normal?? 

**^[[32mINFO ^[[0m[03-23|03:00:03.590] Importing heavy sidechain segment**        ^[[32mblocks^[[0m=2048 ^[[32mstart^[[0m=9679398 ^[[32mend^[[0m=9681445

**Comment by lambda2003** [comment] 2020-03-23 09:34
I just removed all blocks and restarted it. I will keep posting how things are going.

**Comment by meowsbits** [comment] 2020-03-23 11:21
Thanks for the updates. 

The log you posted has a `BAD BLOCK` scenario, which means that the remote your node was downloading from fed you a bad block, and your local chain was rolled back enough to sync around it. This is expected behavior for geth. 

As for the slow sync, it could be caused by many different things... your internet speed, peers available (which can depend on where in the world your node is located, eg. China?), CPU speeds, etc.  Some sections of the chain itself are simply slower to sync than others, too. 

If you keep having the problem and can provide as much context as possible with regard to these possibilities, please let us know!

**Comment by lambda2003** [comment] 2020-03-26 00:43
Thank you for your comment. :) 
FYI. It is slow. Current my block is 9743657 since I start 'geth' three days ago. 

currentBlock: 9743657,
highestBlock: 9743725,
knownStates: 484382762,
pulledStates: 484382762,
startingBlock: 0

**Comment by meowsbits** [comment] 2020-07-23 14:07
Closing since that hasn't had activity for some time. Please reopen if problem has persisted.

**Closed as completed by meowsbits** 2020-07-23 14:07 UTC
Labels: Z0-unconfirmed 🤔, Z1-question 🙋‍♀️
